### ISSUE TITLE
Crash on release when trying to fire weapon

### ISSUE THREAD

**Issue by Silvea12** [godotengine/tps-demo#21] opened 2019-02-04 11:56 UTC
This only seems to happen in release mode, and happens both on windows and linux.
This only happens when the player tries to fire a weapon - enemies can fire weapons with no issues.

In debug, I'll get this
```
ERROR: get_node: Node not found: ../sfx/step
   At: scene/main/node.cpp:1382.
ERROR: _update_caches: AnimationTree: 'running_nogun-cycle', couldn't resolve track:  '../sfx/step'
   At: scene/animation/animation_tree.cpp:581.
Class is disabled for: 24
name: RootMotionView
Class is disabled for: 222
name: RootMotionView
Class is disabled for: 222
name: RootMotionView
Class is disabled for: 222
name: RootMotionView
Class is disabled for: 222
name: RootMotionView
```

But no crash. However, in release mode, I'll get this:
```
ERROR: get_node: Condition ' !node ' is true. returned: __null
   At: scene/main/node.cpp:1382.
ERROR: _update_caches: AnimationTree: 'running_nogun-cycle', couldn't resolve track:  '../sfx/step'
   At: scene/animation/animation_tree.cpp:581.
Class is disabled for: 24
name: RootMotionView
Class is disabled for: 222
name: RootMotionView
Class is disabled for: 222
name: RootMotionView
Class is disabled for: 222
name: RootMotionView
Class is disabled for: 222
name: RootMotionView
ERROR: _ensure_valid_root: Method/Function Failed.
   At: ./core/math/octree.h:573.
Segmentation fault (core dumped)
```

**Comment by aaronfranke** [comment] 2020-02-25 05:44
Are you still experiencing this issue with the latest version of the demo? I can't reproduce it.

**Comment by Calinou** [comment] 2020-06-30 08:06
I'll assume this has been fixed since, closing.

**Closed by Calinou** 2020-06-30 08:06 UTC
Labels: bug

**Comment by Silvea12** [comment] 2020-07-09 18:13
Sorry for the delay. Yeah, can't reproduce as of Godot 3.2.2 and 99e4f80969ecce63d04d11fcb223d1e165999931. Seems all fixed.
