### ISSUE TITLE
Is dim lighting caused by Godot's limitations?

### ISSUE THREAD

**Issue by Pio64** [godotengine/tps-demo#86] opened 2020-10-20 15:48 UTC
This is a very nice demo of some of Godot's capabilities! I've noticed that the scene is very dimly lit and when I opened the project I saw that there are very few lights. I'm wondering if this is caused by Godot's lighting limitations. In my of my own project I've encountered some issues with lighting indoor scenes. I was hoping I would find a solution here, but it seems that developers might have had the same issue as me. Is it possible to improve the lighting in this demo or is it a Godot limitation?

**Comment by Calinou** [comment] 2020-10-20 15:51
No, it's just that lights need to be made stronger. The recent [tonemapping changes](https://github.com/godotengine/tps-demo/pull/84) also made the demo a bit darker than it should be.

**Comment by Pio64** [comment] 2020-10-20 16:08
You said no, but then you confirm that it might be impossible to add enough lights, which is an engine limitation. So it seems that I was correct?

**Comment by Calinou** [comment] 2020-10-20 16:13
@Pio64 Yes, but we can still brighten lights and play with ambient lighting/GIProbe propagation in the current demo :slightly_smiling_face:

**Comment by Calinou** [comment] 2021-12-01 02:50
Closing, as the demo is dark by design: https://github.com/godotengine/tps-demo/pull/111

**Closed by Calinou** 2021-12-01 02:50 UTC
Labels: enhancement
