### ISSUE TITLE
Project display is cropped to vertical orientation

### ISSUE THREAD

**Issue by RyanGPalmer** [godotengine/tps-demo#40] opened 2019-11-27 03:01 UTC
When running the `master` or `download` branches (completely unmodified, no local changes) the screen is cropped to a vertically-oriented section. This is occurring on a 4k monitor which may be a factor. However, changing the monitor resolution to 1920x1080 has no effect. I also tried tweaking display resolution and orientation settings to no avail.

![image](https://user-images.githubusercontent.com/18314366/69689967-30923280-107f-11ea-8f82-6391642f5eee.png)

If I switch to windowed mode, it displays correctly and I am able to resize to full resolution without issue. This may be an engine issue but have not experienced yet this with other projects.

**Comment by Calinou** [comment] 2019-11-27 09:46
Which OS are you on? Also, does it work if you enable **Allow Hidpi** in the Project Settings?

**Comment by RyanGPalmer** [comment] 2019-11-27 17:05
> Which OS are you on? Also, does it work if you enable **Allow Hidpi** in the Project Settings?

Thanks for the response, I'm on Windows 10 preview build 19033. I did try setting the *Allow Hidpi* flag both on and off but it did not have any effect. I also disabled scaling in the Windows display settings and tried various compatibility modes for the program.

My version of Godot is built from the 3.1.1 stable branch.

**Comment by aaronfranke** [comment] 2020-02-25 05:46
Are you still experiencing this issue with the latest version of the demo and with Godot 3.2? I can't reproduce it on my 1080p monitor.

**Comment by Calinou** [comment] 2020-06-30 08:07
I'll assume this issue has been fixed since, closing;

**Closed by Calinou** 2020-06-30 08:07 UTC
Labels: bug, needs testing
